import { access, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export interface RunInitOptions {
  cwd?: string;
}

const CONFIG_FILE = 'nestjs-inertia.config.ts';
const DTS_FILE = 'nestjs-inertia.d.ts';
const GITIGNORE_FILE = '.gitignore';
const GITIGNORE_ENTRY = '.nestjs-inertia/';

const CONFIG_TEMPLATE = `import { defineConfig } from '@dudousxd/nestjs-inertia-codegen';

export default defineConfig({
  pages: {
    glob: 'inertia/pages/**/*.{tsx,vue,svelte}',
  },
});
`;

const DTS_TEMPLATE = `// Auto-generated by nestjs-inertia-codegen. Commit this file.
// Re-run \`nestjs-inertia codegen\` to refresh after adding/removing pages.

import '.nestjs-inertia/index.js';

declare module '@dudousxd/nestjs-inertia' {
  interface InertiaRegistry {
    pages: import('.nestjs-inertia/pages.js').InertiaPages;
    shared: import('.nestjs-inertia/shared.js').InertiaSharedProps;
    routes: import('.nestjs-inertia/routes.js').RouteParamsMap;
  }
}
`;

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function writeIfMissing(filePath: string, content: string, label: string): Promise<void> {
  if (await fileExists(filePath)) {
    console.log(`[nestjs-inertia] ${label} already exists — skipping.`);
    return;
  }
  await writeFile(filePath, content, 'utf8');
  console.log(`[nestjs-inertia] Created ${label}.`);
}

async function patchGitignore(gitignorePath: string): Promise<void> {
  let existing = '';
  if (await fileExists(gitignorePath)) {
    existing = await readFile(gitignorePath, 'utf8');
  }

  // Idempotent: only add the line if it's not already there
  if (existing.split('\n').some((line) => line.trim() === GITIGNORE_ENTRY)) {
    console.log(
      `[nestjs-inertia] ${GITIGNORE_FILE} already contains ${GITIGNORE_ENTRY} — skipping.`,
    );
    return;
  }

  const newContent =
    existing.endsWith('\n') || existing === ''
      ? `${existing}${GITIGNORE_ENTRY}\n`
      : `${existing}\n${GITIGNORE_ENTRY}\n`;

  await writeFile(gitignorePath, newContent, 'utf8');
  console.log(`[nestjs-inertia] Patched ${GITIGNORE_FILE} with ${GITIGNORE_ENTRY}.`);
}

/**
 * `nestjs-inertia init` — scaffold config and type stubs in `cwd`.
 *
 * Idempotent: each file is only written if it does not already exist.
 * The .gitignore entry is only appended if not already present.
 */
export async function runInit(opts: RunInitOptions = {}): Promise<void> {
  const cwd = opts.cwd ?? process.cwd();

  await writeIfMissing(join(cwd, CONFIG_FILE), CONFIG_TEMPLATE, CONFIG_FILE);
  await writeIfMissing(join(cwd, DTS_FILE), DTS_TEMPLATE, DTS_FILE);
  await patchGitignore(join(cwd, GITIGNORE_FILE));
}
