import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { DiscoveredPage } from '../discovery/pages.js';

export async function emitPages(pages: DiscoveredPage[], outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });
  const body = pages
    .map((p) => {
      const propType = p.propsSource ?? 'unknown';
      const key = needsQuotes(p.name) ? `'${p.name}'` : p.name;
      return `  ${key}: ${propType};`;
    })
    .join('\n');
  const content = `// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.\nexport interface InertiaPages {\n${body}\n}\n`;
  await writeFile(join(outDir, 'pages.d.ts'), content, 'utf8');
}

function needsQuotes(name: string): boolean {
  return !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}
