import { mkdir, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { DiscoveredPage } from '../discovery/pages.js';

export interface EmitPagesOptions {
  /** The export name to reference in import() type expressions (default: 'ComponentProps'). */
  propsExport?: string;
  /** When true, infer props from the default export's first parameter instead of a named export. */
  inferFromDefault?: boolean;
}

export async function emitPages(
  pages: DiscoveredPage[],
  outDir: string,
  _options: EmitPagesOptions = {},
): Promise<void> {
  await mkdir(outDir, { recursive: true });

  const pageNameUnion =
    pages.length > 0 ? pages.map((p) => JSON.stringify(p.name)).join(' | ') : 'never';

  const augBody = pages
    .map((p) => {
      const key = needsQuotes(p.name) ? JSON.stringify(p.name) : p.name;
      const valueType = buildAugmentationType(p, outDir);
      return `    ${key}: ${valueType};`;
    })
    .join('\n');

  const propsHelper =
    "\nexport type InertiaProps<K extends InertiaPageName> = import('@dudousxd/nestjs-inertia').InertiaPages[K];\n";

  const content = `// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.\n\nexport type InertiaPageName = ${pageNameUnion};\n${propsHelper}\ndeclare module '@dudousxd/nestjs-inertia' {\n  interface InertiaPages {\n${augBody}\n  }\n}\n`;

  await writeFile(join(outDir, 'pages.d.ts'), content, 'utf8');
}

/**
 * Build the type for a page in the module augmentation.
 * Uses `Parameters<typeof import('...').default>[0]` to infer props
 * directly from the default export — no named export needed.
 */
function buildAugmentationType(page: DiscoveredPage, outDir: string): string {
  let importPath = relative(outDir, page.absolutePath).replace(/\.(tsx?|vue|svelte)$/, '');
  if (!importPath.startsWith('.')) {
    importPath = `./${importPath}`;
  }
  return `Parameters<typeof import('${importPath}').default>[0]`;
}

function needsQuotes(name: string): boolean {
  return !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}
