import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';

export async function emitIndex(outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });
  const content = [
    '// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.',
    "export * from './pages.js';",
    "export * from './shared-props.js';",
    "export * from './routes.js';",
    '',
  ].join('\n');
  await writeFile(join(outDir, 'index.d.ts'), content, 'utf8');
}
