import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { DiscoveredPage } from '../discovery/pages.js';

export async function emitPages(pages: DiscoveredPage[], outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });
  const body = pages
    .map((p) => {
      const propType = p.propsSource ?? 'unknown';
      // Use JSON.stringify for the key so unsafe chars (quotes, backslashes, etc.)
      // are properly escaped. Strip the surrounding double-quotes for TypeScript
      // interface key syntax (TS accepts both 'key' and "key" — we use double).
      const key = needsQuotes(p.name) ? JSON.stringify(p.name) : p.name;
      return `  ${key}: ${propType};`;
    })
    .join('\n');

  // Build InertiaPageName union type
  const pageNameUnion =
    pages.length > 0
      ? pages.map((p) => JSON.stringify(p.name)).join(' | ')
      : 'never';

  // Build module augmentation entries (page name -> true)
  const augBody = pages
    .map((p) => {
      const key = needsQuotes(p.name) ? JSON.stringify(p.name) : p.name;
      return `    ${key}: true;`;
    })
    .join('\n');

  const content =
    `// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.\nexport interface InertiaPages {\n${body}\n}\n` +
    `\nexport type InertiaPageName = ${pageNameUnion};\n` +
    `\ndeclare module '@dudousxd/nestjs-inertia' {\n  interface InertiaPages {\n${augBody}\n  }\n}\n`;

  await writeFile(join(outDir, 'pages.d.ts'), content, 'utf8');
}

function needsQuotes(name: string): boolean {
  return !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}
