import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { RouteDescriptor } from '../discovery/routes.js';

/**
 * Emits `api.ts` into `outDir` for all routes that carry a `.contract`.
 * - GET routes get `queryOptions`
 * - POST/PUT/PATCH/DELETE routes get `mutationOptions`
 */
export async function emitApi(routes: RouteDescriptor[], outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });
  const content = buildApiFile(routes);
  await writeFile(join(outDir, 'api.ts'), content, 'utf8');
}

function buildApiFile(routes: RouteDescriptor[]): string {
  const contracted = routes.filter((r) => r.contract);

  const lines: string[] = [
    '// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.',
    '',
    "import { queryOptions } from '@tanstack/query-core';",
    "import { route } from './routes.js';",
    "import { createFetcher } from '@dudousxd/nestjs-inertia-client';",
    '',
    'export const fetcher = createFetcher();',
    '',
  ];

  // --- ApiRouter type ---
  if (contracted.length === 0) {
    lines.push('export type ApiRouter = Record<string, never>;');
  } else {
    lines.push('export type ApiRouter = {');
    for (const r of contracted) {
      const c = r.contract!;
      const method = c.method.toUpperCase();
      const query = c.contractSource.query ?? 'never';
      const body = method === 'GET' ? 'never' : (c.contractSource.body ?? 'never');
      const response = c.contractSource.response;
      const safeName = JSON.stringify(c.name);
      const safeMethod = JSON.stringify(method);
      lines.push(
        `  ${safeName}: { method: ${safeMethod}; query: ${query}; body: ${body}; response: ${response} };`,
      );
    }
    lines.push('};');
  }

  lines.push('');

  // --- api object ---
  if (contracted.length === 0) {
    lines.push('export const api: Record<string, never> = {} as Record<string, never>;');
  } else {
    lines.push('export const api = {');
    for (const r of contracted) {
      const c = r.contract!;
      const method = c.method.toUpperCase();
      const safeName = JSON.stringify(c.name);
      const safePath = JSON.stringify(c.path);
      const fetcherMethod = method.toLowerCase();

      if (method === 'GET') {
        // queryOptions
        lines.push(`  ${safeName}: {`);
        lines.push(`    queryOptions: (query?: ApiRouter[${safeName}]['query']) =>`);
        lines.push('      queryOptions({');
        lines.push(`        queryKey: [${safeName}, query],`);
        lines.push(
          `        queryFn: () => fetcher.get<ApiRouter[${safeName}]['response']>(route(${safeName} as never) || ${safePath}, { query }),`,
        );
        lines.push('      }),');
        lines.push('  },');
      } else {
        // mutationOptions
        lines.push(`  ${safeName}: {`);
        lines.push('    mutationOptions: () => ({');
        lines.push(
          `      mutationFn: (body: ApiRouter[${safeName}]['body']) => fetcher.${fetcherMethod}<ApiRouter[${safeName}]['response']>(route(${safeName} as never) || ${safePath}, { body }),`,
        );
        lines.push('    }),');
        lines.push('  },');
      }
    }
    lines.push('};');
  }

  lines.push('');

  // --- Infer* mapped types ---
  lines.push("export type InferResponse<K extends keyof ApiRouter> = ApiRouter[K]['response'];");
  lines.push("export type InferBody<K extends keyof ApiRouter> = ApiRouter[K]['body'];");
  lines.push("export type InferQuery<K extends keyof ApiRouter> = ApiRouter[K]['query'];");
  lines.push('');

  return lines.join('\n');
}
