import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

export async function emitIndex(
  outDir: string,
  hasContracts = false,
  hasForms = false,
): Promise<void> {
  await mkdir(outDir, { recursive: true });
  const exports = ["export * from './pages.js';", "export * from './routes.js';"];
  if (hasContracts) {
    exports.push("export * from './api.js';");
  }
  if (hasForms) {
    exports.push("export * from './forms.js';");
  }
  const content = [
    '// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.',
    ...exports,
    '',
  ].join('\n');
  await writeFile(join(outDir, 'index.d.ts'), content, 'utf8');
}
