import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import type { RouteDescriptor } from '../discovery/routes.js';

/**
 * Emits `routes.ts` into `outDir` with:
 * - A `ROUTES` constant mapping name → path
 * - A `RouteName` union type of all route names
 * - A `RouteParams<K>` mapped type using template-literal `infer` to extract `:param` segments
 * - A runtime `route(name, params?)` helper that interpolates path params
 */
export async function emitRoutes(routes: RouteDescriptor[], outDir: string): Promise<void> {
  await mkdir(outDir, { recursive: true });

  const content = buildRoutesFile(routes);
  await writeFile(join(outDir, 'routes.ts'), content, 'utf8');
}

function buildRoutesFile(routes: RouteDescriptor[]): string {
  if (routes.length === 0) {
    return buildEmpty();
  }

  const entries = routes
    .map((r) => `  '${r.name}': '${r.path}',`)
    .join('\n');

  const routeNameUnion = routes.map((r) => `  | '${r.name}'`).join('\n');

  const lines: string[] = [
    '// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.',
    '',
    '/** Map of route name → path pattern. */',
    'export const ROUTES = {',
    entries,
    '} as const;',
    '',
    '/** Union of all known route names. */',
    'export type RouteName =',
    routeNameUnion + ';',
    '',
    '/**',
    ' * Extracts path-parameter names from a route path string.',
    ' * `ExtractParams<"/users/:id">` → `"id"`',
    ' */',
    'export type ExtractParams<Path extends string> =',
    '  Path extends `${string}:${infer Param}/${infer Rest}`',
    '    ? Param | ExtractParams<`/${Rest}`>',
    '    : Path extends `${string}:${infer Param}`',
    '      ? Param',
    '      : never;',
    '',
    '/**',
    ' * Mapped type: given a `RouteName`, returns an object with each path param as `string`.',
    ' * `RouteParams<"UsersController.show">` → `{ id: string }`',
    ' * `RouteParams<"UsersController.list">` → `Record<string, never>`',
    ' */',
    'export type RouteParams<K extends RouteName> =',
    '  ExtractParams<(typeof ROUTES)[K]> extends never',
    '    ? Record<string, never>',
    '    : { [P in ExtractParams<(typeof ROUTES)[K]>]: string };',
    '',
    '/**',
    ' * Build a URL from a named route, interpolating path params.',
    ' *',
    ' * @example',
    " * route('UsersController.show', { id: '42' }) // → '/users/42'",
    " * route('UsersController.list')                // → '/users'",
    ' */',
    'export function route<K extends RouteName>(',
    '  name: K,',
    '  ...args: ExtractParams<(typeof ROUTES)[K]> extends never',
    '    ? []',
    '    : [params: RouteParams<K>]',
    '): string {',
    '  let path: string = ROUTES[name];',
    '  const params = args[0] as Record<string, string> | undefined;',
    '  if (params) {',
    '    path = path.replace(/:([^/]+)/g, (_, key) => {',
    "      const val = params[key];",
    "      if (val === undefined) throw new Error(`Missing route param: ${key}`);",
    '      return encodeURIComponent(val);',
    '    });',
    '  }',
    '  return path;',
    '}',
    '',
  ];

  return lines.join('\n');
}

function buildEmpty(): string {
  return [
    '// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.',
    '',
    'export const ROUTES = {} as const;',
    'export type RouteName = never;',
    'export type ExtractParams<_Path extends string> = never;',
    'export type RouteParams<_K extends RouteName> = Record<string, never>;',
    'export function route(_name: never): string { return ""; }',
    '',
  ].join('\n');
}
