import { mkdir, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { ResolvedFormsConfig } from '../config/types.js';
import type { RouteDescriptor, TypeRef } from '../discovery/types.js';

interface FormSchemaSource {
  /** `bodyZodRef`/`queryZodRef` re-export (Path A named const). */
  ref: TypeRef | null;
  /** Raw zod source text to inline (Path A inline call / Path B synthesized). */
  text: string | null;
}

interface FormEntry {
  routeName: string;
  /** PascalCase base, e.g. `Login` (or `AuthLogin` on collision). */
  baseName: string;
  body: FormSchemaSource | undefined;
  query: FormSchemaSource | undefined;
  nestedSchemas: Record<string, string> | null;
  warnings: string[];
}

/**
 * Emits `forms.ts` into `outDir` — re-exported (Path A) or inlined/synthesized
 * (Path A inline / Path B) zod schemas per validatable route, plus a
 * `formSchemas` name→schema map.
 *
 * Returns `true` when a `forms.ts` was written (drives the index export).
 */
export async function emitForms(
  routes: RouteDescriptor[],
  outDir: string,
  config?: ResolvedFormsConfig,
): Promise<boolean> {
  if (config && config.enabled === false) return false;

  const entries = collectFormEntries(routes);
  if (entries.length === 0) return false;

  await mkdir(outDir, { recursive: true });
  const content = buildFormsFile(entries, outDir, config);
  await writeFile(join(outDir, 'forms.ts'), content, 'utf8');
  return true;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function hasSchema(src: FormSchemaSource | undefined): boolean {
  return !!src && (src.ref !== null || src.text !== null);
}

/** PascalCase from a single dot/identifier segment. */
function pascal(segment: string): string {
  return segment
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

/**
 * PascalCase base name for a route. Uses the method segment (last dot-part);
 * the full dotted name is used to disambiguate collisions.
 */
function deriveBaseName(routeName: string): { method: string; full: string } {
  const segments = routeName.split('.');
  const method = pascal(segments[segments.length - 1] ?? routeName);
  const full = segments.map(pascal).join('');
  return { method, full };
}

function collectFormEntries(routes: RouteDescriptor[]): FormEntry[] {
  // Deterministic ordering: routes sorted by name.
  const sorted = [...routes].filter((r) => r.contract).sort((a, b) => a.name.localeCompare(b.name));

  // First pass: which base (method-only) names collide?
  const methodNameCounts = new Map<string, number>();
  const candidates: Array<{ route: RouteDescriptor; method: string; full: string }> = [];
  for (const route of sorted) {
    const cs = route.contract!.contractSource;
    const body: FormSchemaSource = { ref: cs.bodyZodRef ?? null, text: cs.bodyZodText ?? null };
    const query: FormSchemaSource = { ref: cs.queryZodRef ?? null, text: cs.queryZodText ?? null };
    if (!hasSchema(body) && !hasSchema(query)) continue;
    const { method, full } = deriveBaseName(route.name);
    methodNameCounts.set(method, (methodNameCounts.get(method) ?? 0) + 1);
    candidates.push({ route, method, full });
  }

  const entries: FormEntry[] = [];
  for (const { route, method, full } of candidates) {
    const cs = route.contract!.contractSource;
    const collision = (methodNameCounts.get(method) ?? 0) > 1;
    const baseName = collision ? full : method;
    const body: FormSchemaSource = { ref: cs.bodyZodRef ?? null, text: cs.bodyZodText ?? null };
    const query: FormSchemaSource = { ref: cs.queryZodRef ?? null, text: cs.queryZodText ?? null };
    entries.push({
      routeName: route.name,
      baseName,
      body: hasSchema(body) ? body : undefined,
      query: hasSchema(query) ? query : undefined,
      nestedSchemas: cs.formNestedSchemas ?? null,
      warnings: cs.formWarnings ?? [],
    });
  }
  return entries;
}

/** Relative import specifier from outDir to a source file (no extension). */
function relImport(outDir: string, filePath: string): string {
  let relPath = relative(outDir, filePath).replace(/\.ts$/, '');
  if (!relPath.startsWith('.')) relPath = `./${relPath}`;
  return relPath;
}

/** The root identifier of a ref name like `loginContract.body` → `loginContract`. */
function refRootIdentifier(refName: string): string {
  return refName.split('.')[0] ?? refName;
}

function buildFormsFile(
  entries: FormEntry[],
  outDir: string,
  config?: ResolvedFormsConfig,
): string {
  const zodImport = config?.zodImport ?? 'zod';
  const lines: string[] = [
    '// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.',
    `import { z } from '${zodImport}';`,
  ];

  // Collect re-export imports grouped by file. Alias on identifier collision.
  const importsByFile = new Map<string, Set<string>>();
  const refAlias = new Map<string, string>(); // `${filePath}\0${root}` → alias
  for (const entry of entries) {
    for (const src of [entry.body, entry.query]) {
      // Only a ref WITHOUT inline text produces an import (text is preferred).
      if (src?.ref && !src.text) {
        const root = refRootIdentifier(src.ref.name);
        const set = importsByFile.get(src.ref.filePath) ?? new Set<string>();
        set.add(root);
        importsByFile.set(src.ref.filePath, set);
      }
    }
  }

  if (importsByFile.size > 0) {
    const emitted = new Set<string>();
    for (const [filePath, roots] of [...importsByFile.entries()].sort()) {
      const relPath = relImport(outDir, filePath);
      const specifiers: string[] = [];
      for (const root of [...roots].sort()) {
        if (emitted.has(root)) {
          const alias = `${root}_${emitted.size}`;
          specifiers.push(`${root} as ${alias}`);
          emitted.add(alias);
          refAlias.set(`${filePath}\0${root}`, alias);
        } else {
          specifiers.push(root);
          emitted.add(root);
          refAlias.set(`${filePath}\0${root}`, root);
        }
      }
      lines.push(`import { ${specifiers.join(', ')} } from '${relPath}';`);
    }
  }

  lines.push('');

  const mapEntries: string[] = [];

  for (const entry of entries) {
    lines.push(`// ${entry.routeName}`);

    if (entry.warnings && entry.warnings.length > 0) {
      for (const w of entry.warnings) {
        lines.push(`// warning: ${w}`);
      }
    }

    // Hoist nested named schemas referenced by this entry (Path B).
    if (entry.nestedSchemas) {
      for (const [name, text] of Object.entries(entry.nestedSchemas)) {
        lines.push(`const ${name} = ${text};`);
      }
    }

    if (entry.body) {
      const schemaName = `${entry.baseName}BodySchema`;
      const typeName = `${entry.baseName}Body`;
      lines.push(`export const ${schemaName} = ${renderSchema(entry.body, outDir, refAlias)};`);
      lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
      mapEntries.push(`  ${JSON.stringify(entry.routeName)}: ${schemaName},`);
    }

    if (entry.query) {
      const schemaName = `${entry.baseName}QuerySchema`;
      const typeName = `${entry.baseName}Query`;
      lines.push(`export const ${schemaName} = ${renderSchema(entry.query, outDir, refAlias)};`);
      lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
    }

    lines.push('');
  }

  lines.push('/** Route name → body schema map. */');
  lines.push('export const formSchemas = {');
  lines.push(...mapEntries);
  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}

function renderSchema(
  src: FormSchemaSource,
  outDir: string,
  refAlias: Map<string, string>,
): string {
  // Prefer inlining the raw zod text: re-exporting a named const from its source
  // (typically a controller) would pull server-only deps into the client bundle.
  // The text is byte-identical to the contract schema, so parity is preserved.
  if (src.text) return src.text;
  if (src.ref) {
    const root = refRootIdentifier(src.ref.name);
    const alias = refAlias.get(`${src.ref.filePath}\0${root}`) ?? root;
    // Replace the root identifier with its (possibly aliased) import binding.
    const member = src.ref.name.slice(root.length); // e.g. `.body`
    return `${alias}${member}`;
  }
  return 'z.unknown()';
}
