import { mkdir, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import type { ResolvedFormsConfig } from '../config/types.js';
import type { RouteDescriptor, TypeRef } from '../discovery/types.js';

interface FormSchemaSource {
  /** `bodyZodRef`/`queryZodRef` re-export (Path A named const). */
  ref: TypeRef | null;
  /** Raw zod source text to inline (Path A inline call / Path B synthesized). */
  text: string | null;
}

interface FormEntry {
  routeName: string;
  /** PascalCase base, e.g. `Login` (or `AuthLogin` on collision). */
  baseName: string;
  body: FormSchemaSource | undefined;
  query: FormSchemaSource | undefined;
  nestedSchemas: Record<string, string> | null;
  warnings: string[];
}

/**
 * Emits `forms.ts` into `outDir` — re-exported (Path A) or inlined/synthesized
 * (Path A inline / Path B) zod schemas per validatable route, plus a
 * `formSchemas` name→schema map.
 *
 * Returns `true` when a `forms.ts` was written (drives the index export).
 */
export async function emitForms(
  routes: RouteDescriptor[],
  outDir: string,
  config?: ResolvedFormsConfig,
): Promise<boolean> {
  if (config && config.enabled === false) return false;

  const entries = collectFormEntries(routes);
  if (entries.length === 0) return false;

  await mkdir(outDir, { recursive: true });
  const content = buildFormsFile(entries, outDir, config);
  await writeFile(join(outDir, 'forms.ts'), content, 'utf8');
  return true;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function hasSchema(src: FormSchemaSource | undefined): boolean {
  return !!src && (src.ref !== null || src.text !== null);
}

/** PascalCase from a single dot/identifier segment. */
function pascal(segment: string): string {
  return segment
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
}

/**
 * PascalCase base name for a route. Uses the method segment (last dot-part);
 * the full dotted name is used to disambiguate collisions.
 */
function deriveBaseName(routeName: string): { method: string; full: string } {
  const segments = routeName.split('.');
  const method = pascal(segments[segments.length - 1] ?? routeName);
  const full = segments.map(pascal).join('');
  return { method, full };
}

function collectFormEntries(routes: RouteDescriptor[]): FormEntry[] {
  // Deterministic ordering: routes sorted by name.
  const sorted = [...routes].filter((r) => r.contract).sort((a, b) => a.name.localeCompare(b.name));

  // First pass: which base (method-only) names collide?
  const methodNameCounts = new Map<string, number>();
  const candidates: Array<{ route: RouteDescriptor; method: string; full: string }> = [];
  for (const route of sorted) {
    const cs = route.contract!.contractSource;
    const body: FormSchemaSource = { ref: cs.bodyZodRef ?? null, text: cs.bodyZodText ?? null };
    const query: FormSchemaSource = { ref: cs.queryZodRef ?? null, text: cs.queryZodText ?? null };
    if (!hasSchema(body) && !hasSchema(query)) continue;
    const { method, full } = deriveBaseName(route.name);
    methodNameCounts.set(method, (methodNameCounts.get(method) ?? 0) + 1);
    candidates.push({ route, method, full });
  }

  const entries: FormEntry[] = [];
  for (const { route, method, full } of candidates) {
    const cs = route.contract!.contractSource;
    const collision = (methodNameCounts.get(method) ?? 0) > 1;
    const baseName = collision ? full : method;
    const body: FormSchemaSource = { ref: cs.bodyZodRef ?? null, text: cs.bodyZodText ?? null };
    const query: FormSchemaSource = { ref: cs.queryZodRef ?? null, text: cs.queryZodText ?? null };
    entries.push({
      routeName: route.name,
      baseName,
      body: hasSchema(body) ? body : undefined,
      query: hasSchema(query) ? query : undefined,
      nestedSchemas: cs.formNestedSchemas ?? null,
      warnings: cs.formWarnings ?? [],
    });
  }
  return entries;
}

/** Relative import specifier from outDir to a source file (no extension). */
function relImport(outDir: string, filePath: string): string {
  let relPath = relative(outDir, filePath).replace(/\.ts$/, '');
  if (!relPath.startsWith('.')) relPath = `./${relPath}`;
  return relPath;
}

/** The root identifier of a ref name like `loginContract.body` → `loginContract`. */
function refRootIdentifier(refName: string): string {
  return refName.split('.')[0] ?? refName;
}

function buildFormsFile(
  entries: FormEntry[],
  outDir: string,
  config?: ResolvedFormsConfig,
): string {
  const zodImport = config?.zodImport ?? 'zod';
  const lines: string[] = [
    '// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.',
    `import { z } from '${zodImport}';`,
  ];

  // Collect re-export imports grouped by file. Alias on identifier collision.
  const importsByFile = new Map<string, Set<string>>();
  const refAlias = new Map<string, string>(); // `${filePath}\0${root}` → alias
  for (const entry of entries) {
    for (const src of [entry.body, entry.query]) {
      // Only a ref WITHOUT inline text produces an import (text is preferred).
      if (src?.ref && !src.text) {
        const root = refRootIdentifier(src.ref.name);
        const set = importsByFile.get(src.ref.filePath) ?? new Set<string>();
        set.add(root);
        importsByFile.set(src.ref.filePath, set);
      }
    }
  }

  if (importsByFile.size > 0) {
    const emitted = new Set<string>();
    for (const [filePath, roots] of [...importsByFile.entries()].sort()) {
      const relPath = relImport(outDir, filePath);
      const specifiers: string[] = [];
      for (const root of [...roots].sort()) {
        if (emitted.has(root)) {
          const alias = `${root}_${emitted.size}`;
          specifiers.push(`${root} as ${alias}`);
          emitted.add(alias);
          refAlias.set(`${filePath}\0${root}`, alias);
        } else {
          specifiers.push(root);
          emitted.add(root);
          refAlias.set(`${filePath}\0${root}`, root);
        }
      }
      lines.push(`import { ${specifiers.join(', ')} } from '${relPath}';`);
    }
  }

  lines.push('');

  // ── Hoist nested schemas exactly once (dedup), disambiguating collisions ──
  // Each entry carries a `nestedSchemas` map (name → zod text) whose texts may
  // reference each other (and themselves) by name. A nested schema shared by N
  // endpoints must be declared ONCE; two unrelated schemas that happen to share
  // a name must NOT collapse into one. `planNestedSchemas` produces a global
  // registry of unique declarations plus a per-entry rename map applied to that
  // entry's body/query text.
  const { globalSchemas, renamesByEntry } = planNestedSchemas(entries);

  if (globalSchemas.size > 0) {
    lines.push('// Hoisted nested schemas (shared across endpoints).');
    for (const [name, text] of globalSchemas) {
      lines.push(`const ${name} = ${text};`);
    }
    lines.push('');
  }

  const mapEntries: string[] = [];

  for (const entry of entries) {
    lines.push(`// ${entry.routeName}`);

    if (entry.warnings && entry.warnings.length > 0) {
      for (const w of entry.warnings) {
        lines.push(`// warning: ${w}`);
      }
    }

    const rename = renamesByEntry.get(entry) ?? null;

    if (entry.body) {
      const schemaName = `${entry.baseName}BodySchema`;
      const typeName = `${entry.baseName}Body`;
      const text = applyRenames(renderSchema(entry.body, outDir, refAlias), rename);
      lines.push(`export const ${schemaName} = ${text};`);
      lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
      mapEntries.push(`  ${JSON.stringify(entry.routeName)}: ${schemaName},`);
    }

    if (entry.query) {
      const schemaName = `${entry.baseName}QuerySchema`;
      const typeName = `${entry.baseName}Query`;
      const text = applyRenames(renderSchema(entry.query, outDir, refAlias), rename);
      lines.push(`export const ${schemaName} = ${text};`);
      lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
    }

    lines.push('');
  }

  lines.push('/** Route name → body schema map. */');
  lines.push('export const formSchemas = {');
  lines.push(...mapEntries);
  lines.push('} as const;');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Nested-schema hoisting: dedup + collision disambiguation + recursion guard.
// ---------------------------------------------------------------------------

interface NestedSchemaPlan {
  /** Final unique name → declaration text, emitted once at the top. */
  globalSchemas: Map<string, string>;
  /** Per-entry name-rewrite map applied to that entry's body/query text. */
  renamesByEntry: Map<FormEntry, Map<string, string>>;
}

/**
 * Replace whole-identifier occurrences of each `from` name with its `to` name.
 * Uses a word boundary so `ColumnFilterSchema` is not matched inside
 * `ColumnFilterSchemaExtra`. A no-op when `renames` is null/empty.
 */
function applyRenames(text: string, renames: Map<string, string> | null): string {
  if (!renames || renames.size === 0) return text;
  let out = text;
  for (const [from, to] of renames) {
    if (from === to) continue;
    out = out.replace(new RegExp(`\\b${escapeRegExp(from)}\\b`, 'g'), to);
  }
  return out;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Does `text` reference its own declaration name (self-referential)? */
function isSelfReferential(name: string, text: string): boolean {
  return new RegExp(`\\b${escapeRegExp(name)}\\b`).test(text);
}

/**
 * Build the global hoist registry + per-entry renames.
 *
 * Invariants enforced:
 *  - Each unique (name, shape) pair is declared exactly once.
 *  - Same name + same shape across entries → shared (no duplicate `const`).
 *  - Same name + DIFFERENT shape → the later entry's copy is suffixed
 *    (`Name_2`, `Name_3`, …) and every reference inside that entry is rewritten,
 *    so the two distinct shapes never collide into one wrong schema.
 *  - A self-referential (recursive) declaration is degraded to a valid
 *    `z.unknown()` placeholder — never emitted as `const X = (… X …)` without a
 *    type annotation (which would be implicit-any / fail to compile).
 */
function planNestedSchemas(entries: FormEntry[]): NestedSchemaPlan {
  const globalSchemas = new Map<string, string>();
  // Canonical text already registered under a given final name (for shape match).
  const renamesByEntry = new Map<FormEntry, Map<string, string>>();

  for (const entry of entries) {
    if (!entry.nestedSchemas) continue;
    const local = Object.entries(entry.nestedSchemas);
    if (local.length === 0) continue;

    // Resolve a final, collision-free name for each local schema name. Iterate
    // to a fixpoint so that a rename of schema B (referenced by schema A) is
    // reflected when comparing A's text against the global registry.
    const rename = new Map<string, string>();
    for (const [name] of local) rename.set(name, name);

    // Helper: the entry-local text for a name with the CURRENT rename map applied.
    const textFor = (name: string): string => {
      const raw = entry.nestedSchemas?.[name] ?? '';
      return applyRenames(raw, rename);
    };

    let changed = true;
    let guard = 0;
    while (changed && guard < local.length + 2) {
      changed = false;
      guard += 1;
      for (const [name] of local) {
        const finalName = rename.get(name) ?? name;
        const text = textFor(name);
        const existing = globalSchemas.get(finalName);
        if (existing === undefined) continue; // not yet registered → fine
        if (existing === text) continue; // same shape already registered → reuse
        // Collision: same name, different shape. Pick a fresh suffixed name.
        let i = 2;
        let candidate = `${name}_${i}`;
        while (
          (globalSchemas.has(candidate) && globalSchemas.get(candidate) !== textFor(name)) ||
          [...rename.values()].includes(candidate)
        ) {
          i += 1;
          candidate = `${name}_${i}`;
        }
        rename.set(name, candidate);
        changed = true;
      }
    }

    // Register each local schema under its final name, degrading recursion.
    for (const [name] of local) {
      const finalName = rename.get(name) ?? name;
      let text = textFor(name);
      if (isSelfReferential(finalName, text)) {
        text = 'z.unknown() /* recursive type — not expanded */';
      }
      const existing = globalSchemas.get(finalName);
      if (existing === undefined) {
        globalSchemas.set(finalName, text);
      }
      // If existing === text → already registered (shared). If it somehow still
      // differs after the fixpoint, keep the first registration and let the
      // rename map (which only rewrites references) point references elsewhere;
      // this branch is unreachable given the loop above but is a safe no-op.
    }

    renamesByEntry.set(entry, rename);
  }

  return { globalSchemas, renamesByEntry };
}

function renderSchema(
  src: FormSchemaSource,
  outDir: string,
  refAlias: Map<string, string>,
): string {
  // Prefer inlining the raw zod text: re-exporting a named const from its source
  // (typically a controller) would pull server-only deps into the client bundle.
  // The text is byte-identical to the contract schema, so parity is preserved.
  if (src.text) return src.text;
  if (src.ref) {
    const root = refRootIdentifier(src.ref.name);
    const alias = refAlias.get(`${src.ref.filePath}\0${root}`) ?? root;
    // Replace the root identifier with its (possibly aliased) import binding.
    const member = src.ref.name.slice(root.length); // e.g. `.body`
    return `${alias}${member}`;
  }
  return 'z.unknown()';
}
