// Auto-generated by nestjs-inertia-codegen. Commit this file.
// Re-run `nestjs-inertia codegen` to refresh after adding/removing pages.

import '.nestjs-inertia/index.js';

declare module '@dudousxd/nestjs-inertia' {
  interface InertiaRegistry {
    pages: import('.nestjs-inertia/pages.js').InertiaPages;
    routes: import('.nestjs-inertia/routes.js').RouteParamsMap;
  }
}
