// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.

/** Map of route name → path pattern. */
export const ROUTES = {
  'DashboardController.index': '/dashboard',
  'posts.list': '/api/posts',
} as const;

/** Union of all known route names. */
export type RouteName = 'DashboardController.index' | 'posts.list';

/**
 * Extracts path-parameter names from a route path string.
 * `ExtractParams<"/users/:id">` → `"id"`
 */
export type ExtractParams<Path extends string> =
  Path extends `${string}:${infer Param}/${infer Rest}`
    ? Param | ExtractParams<`/${Rest}`>
    : Path extends `${string}:${infer Param}`
      ? Param
      : never;

/**
 * Mapped type: given a `RouteName`, returns an object with each path param as `string`.
 * `RouteParams<"DashboardController.index">` → `Record<string, never>`
 * `RouteParams<"posts.list">` → `Record<string, never>`
 */
export type RouteParams<K extends RouteName> =
  ExtractParams<(typeof ROUTES)[K]> extends never
    ? Record<string, never>
    : { [P in ExtractParams<(typeof ROUTES)[K]>]: string };

/**
 * Map of every route name to its resolved params object.
 * Use this for `InertiaRegistry` module augmentation.
 */
export type RouteParamsMap = { [K in RouteName]: RouteParams<K> };

/**
 * Build a URL from a named route, interpolating path params.
 *
 * @example
 * route('DashboardController.index')   // → '/dashboard'
 * route('posts.list')                  // → '/api/posts'
 */
export function route<K extends RouteName>(
  name: K,
  ...args: ExtractParams<(typeof ROUTES)[K]> extends never
    ? []
    : [params: RouteParams<K>]
): string {
  let path: string = ROUTES[name];
  const params = args[0] as Record<string, string> | undefined;
  if (params) {
    path = path.replace(/:([^/]+)/g, (_, key) => {
      const val = params[key];
      if (val === undefined) throw new Error(`Missing route param: ${key}`);
      return encodeURIComponent(val);
    });
  }
  return path;
}
