// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.

import { queryOptions as _queryOptions } from '@tanstack/react-query';
import { router } from '@inertiajs/react';
import { route, ROUTES, type RouteName, type ExtractParams, type RouteParams } from './routes.js';
import { fetcher } from '@/lib/api';

export type ApiRouter = {
  dashboard: {
    root: { method: "GET"; url: "/"; params: never; query: never; body: never; response: Awaited<ReturnType<import('../src/dashboard.controller').DashboardController['root']>>; filterFields: never };
    index: { method: "GET"; url: "/dashboard"; params: never; query: never; body: never; response: Awaited<ReturnType<import('../src/dashboard.controller').DashboardController['index']>>; filterFields: never };
  };
  users: {
    list: { method: "GET"; url: "/api/users"; params: never; query: { active?: boolean | undefined }; body: never; response: Awaited<ReturnType<import('../src/users.controller').UsersController['list']>>; filterFields: never };
  };
};

export const api = {
  dashboard: {
    root: {
      queryKey: (query?: ApiRouter["dashboard"]["root"]['query']) => query !== undefined ? ["dashboard.root", query] as const : ["dashboard.root"] as const,
      queryOptions: (query?: ApiRouter["dashboard"]["root"]['query']) =>
        _queryOptions({
          queryKey: query !== undefined ? ["dashboard.root", query] as const : ["dashboard.root"] as const,
          queryFn: () => fetcher.get<ApiRouter["dashboard"]["root"]['response']>(route("dashboard.root" as never) || "/", { query: query as Record<string, unknown> | undefined }),
        }),
      infiniteQueryOptions: (query?: ApiRouter["dashboard"]["root"]['query']) => ({
        queryKey: query !== undefined ? ["dashboard.root", query] as const : ["dashboard.root"] as const,
        queryFn: ({ pageParam }: { pageParam: number }) => fetcher.get<ApiRouter["dashboard"]["root"]['response']>(route("dashboard.root" as never) || "/", { query: { ...(query != null ? query : {}), page: pageParam } as Record<string, unknown> }),
        initialPageParam: 1,
        getNextPageParam: (lastPage: ApiRouter["dashboard"]["root"]['response']) => {
          const meta = (lastPage as any)?.meta;
          if (meta?.page != null && meta?.lastPage != null) {
            return meta.page < meta.lastPage ? meta.page + 1 : undefined;
          }
          return undefined;
        },
      }),
    },
    index: {
      queryKey: (query?: ApiRouter["dashboard"]["index"]['query']) => query !== undefined ? ["dashboard.index", query] as const : ["dashboard.index"] as const,
      queryOptions: (query?: ApiRouter["dashboard"]["index"]['query']) =>
        _queryOptions({
          queryKey: query !== undefined ? ["dashboard.index", query] as const : ["dashboard.index"] as const,
          queryFn: () => fetcher.get<ApiRouter["dashboard"]["index"]['response']>(route("dashboard.index" as never) || "/dashboard", { query: query as Record<string, unknown> | undefined }),
        }),
      infiniteQueryOptions: (query?: ApiRouter["dashboard"]["index"]['query']) => ({
        queryKey: query !== undefined ? ["dashboard.index", query] as const : ["dashboard.index"] as const,
        queryFn: ({ pageParam }: { pageParam: number }) => fetcher.get<ApiRouter["dashboard"]["index"]['response']>(route("dashboard.index" as never) || "/dashboard", { query: { ...(query != null ? query : {}), page: pageParam } as Record<string, unknown> }),
        initialPageParam: 1,
        getNextPageParam: (lastPage: ApiRouter["dashboard"]["index"]['response']) => {
          const meta = (lastPage as any)?.meta;
          if (meta?.page != null && meta?.lastPage != null) {
            return meta.page < meta.lastPage ? meta.page + 1 : undefined;
          }
          return undefined;
        },
      }),
    },
  },
  users: {
    list: {
      queryKey: (query?: ApiRouter["users"]["list"]['query']) => query !== undefined ? ["users.list", query] as const : ["users.list"] as const,
      queryOptions: (query?: ApiRouter["users"]["list"]['query']) =>
        _queryOptions({
          queryKey: query !== undefined ? ["users.list", query] as const : ["users.list"] as const,
          queryFn: () => fetcher.get<ApiRouter["users"]["list"]['response']>(route("users.list" as never) || "/api/users", { query: query as Record<string, unknown> | undefined }),
        }),
      infiniteQueryOptions: (query?: ApiRouter["users"]["list"]['query']) => ({
        queryKey: query !== undefined ? ["users.list", query] as const : ["users.list"] as const,
        queryFn: ({ pageParam }: { pageParam: number }) => fetcher.get<ApiRouter["users"]["list"]['response']>(route("users.list" as never) || "/api/users", { query: { ...(query != null ? query : {}), page: pageParam } as Record<string, unknown> }),
        initialPageParam: 1,
        getNextPageParam: (lastPage: ApiRouter["users"]["list"]['response']) => {
          const meta = (lastPage as any)?.meta;
          if (meta?.page != null && meta?.lastPage != null) {
            return meta.page < meta.lastPage ? meta.page + 1 : undefined;
          }
          return undefined;
        },
      }),
    },
  },
};

type _RouterAt<R, P extends string> = P extends `${infer Head}.${infer Tail}`
  ? Head extends keyof R ? _RouterAt<R[Head], Tail> : never
  : P extends keyof R ? R[P] : never;

type ResolveByName<K extends string, Field extends string> = _RouterAt<ApiRouter, K> extends infer R ? Field extends keyof R ? R[Field] : never : never;

type _LeafValues<T> = T extends { method: string; url: string }
  ? T
  : T extends object ? _LeafValues<T[keyof T]> : never;

type ResolveByPath<M extends string, U extends string, Field extends string> = _LeafValues<ApiRouter> extends infer L
  ? L extends { method: M; url: U }
    ? Field extends keyof L ? L[Field] : never
    : never
  : never;

export namespace Route {
  export type Response<K extends string> = ResolveByName<K, "response">;
  export type Body<K extends string> = ResolveByName<K, "body">;
  export type Query<K extends string> = ResolveByName<K, "query">;
  export type Params<K extends string> = ResolveByName<K, "params">;
  export type Error<K extends string> = ResolveByName<K, "error">;
  export type FilterFields<K extends string> = ResolveByName<K, "filterFields">;
  export type Request<K extends string> = {
    body: Body<K>;
    query: Query<K>;
    params: Params<K>;
  };
}

export namespace Path {
  export type Response<M extends string, U extends string> = ResolveByPath<M, U, "response">;
  export type Body<M extends string, U extends string> = ResolveByPath<M, U, "body">;
  export type Query<M extends string, U extends string> = ResolveByPath<M, U, "query">;
  export type Params<M extends string, U extends string> = ResolveByPath<M, U, "params">;
  export type Error<M extends string, U extends string> = ResolveByPath<M, U, "error">;
  export type FilterFields<M extends string, U extends string> = ResolveByPath<M, U, "filterFields">;
}

export type NavigateOptions = {
  method?: string;
  data?: Record<string, unknown>;
  preserveState?: boolean;
  preserveScroll?: boolean;
  replace?: boolean;
};

/**
 * Type-safe navigation using Inertia router.
 * Resolves the URL from the named route and calls `router.visit()`.
 */
export function navigate<K extends RouteName>(
  name: K,
  ...args: ExtractParams<(typeof ROUTES)[K]> extends never
    ? [options?: NavigateOptions]
    : [options: { params: RouteParams<K> } & NavigateOptions]
): void {
  const [options] = args as [({ params?: Record<string, string> } & NavigateOptions) | undefined];
  const url = route(name as never, (options as any)?.params as never);
  const { params: _p, ...visitOptions } = options ?? {} as any;
  router.visit(url, visitOptions);
}
