// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.
import { z } from 'zod';

// users.list
export const ListQuerySchema = z.object({ active: z.boolean().optional() });
export type ListQuery = z.infer<typeof ListQuerySchema>;

/** Route name → body schema map. */
export const formSchemas = {
} as const;
