// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.
import { z } from 'zod';

// auth.login
export const LoginBodySchema = z.object({
    email: z.string().email(),
    password: z.string().min(8),
  });
export type LoginBody = z.infer<typeof LoginBodySchema>;

// users.list
export const ListQuerySchema = z.object({ active: z.boolean().optional() });
export type ListQuery = z.infer<typeof ListQuerySchema>;

/** Route name → body schema map for useInertiaForm-by-name ergonomics. */
export const formSchemas = {
  "auth.login": LoginBodySchema,
} as const;
