// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.
export interface InertiaPages {
  'inertia/pages/Dashboard': {
  user: { id: number; name: string };
  count: number;
};
  'inertia/pages/Users': {};
}
