// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.

export type InertiaPageName = "Dashboard" | "Login" | "Users";

export type InertiaProps<K extends InertiaPageName> = import('@dudousxd/nestjs-inertia').InertiaPages[K];

declare module '@dudousxd/nestjs-inertia' {
  interface InertiaPages {
    Dashboard: Parameters<typeof import('../inertia/pages/Dashboard').default>[0];
    Login: Parameters<typeof import('../inertia/pages/Login').default>[0];
    Users: Parameters<typeof import('../inertia/pages/Users').default>[0];
  }

  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  interface InertiaSharedProps extends Awaited<ReturnType<typeof import('/home/dudousxd/personal/nestjs-inertia/examples/express-react/src/shared-props').getSharedProps>> {}
}
