// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.
export interface InertiaPages {
  'inertia/pages/Dashboard': {
  user: { name: string };
  items: number;
};
  'inertia/pages/Items': Record<string, never>;
}
