// Generated by @dudousxd/nestjs-inertia-codegen. Do not edit.

/** Map of route name → path pattern. */
export const ROUTES = {
  "DashboardController.index": "/dashboard",
  "items.list": "/api/items",
} as const;

/** Union of all known route names. */
export type RouteName = "DashboardController.index" | "items.list";

/**
 * Extracts path-parameter names from a route path string.
 * `ExtractParams<"/users/:id">` → `"id"`
 */
export type ExtractParams<Path extends string> =
  Path extends `${string}:${infer Param}/${infer Rest}`
    ? Param | ExtractParams<`/${Rest}`>
    : Path extends `${string}:${infer Param}`
      ? Param
      : never;

/**
 * Mapped type: given a `RouteName`, returns an object with each path param as `string`.
 */
export type RouteParams<K extends RouteName> =
  ExtractParams<(typeof ROUTES)[K]> extends never
    ? Record<string, never>
    : { [P in ExtractParams<(typeof ROUTES)[K]>]: string };

/**
 * Map of every route name to its resolved params object.
 * Use this for `InertiaRegistry` module augmentation.
 */
export type RouteParamsMap = { [K in RouteName]: RouteParams<K> };

/**
 * Build a URL from a named route, interpolating path params and appending query string.
 *
 * @example
 * route('DashboardController.index')   // → '/dashboard'
 * route('items.list')                  // → '/api/items'
 * route('items.list', undefined, { page: 2 }) // → '/api/items?page=2'
 */
export function route<K extends RouteName>(
  name: K,
  ...args: ExtractParams<(typeof ROUTES)[K]> extends never
    ? [params?: undefined, query?: Record<string, unknown>]
    : [params: RouteParams<K>, query?: Record<string, unknown>]
): string {
  const [params, query] = args as [Record<string, string> | undefined, Record<string, unknown> | undefined];
  let path: string = ROUTES[name];
  if (params) {
    path = path.replace(/:([^/]+)/g, (_, key) => {
      const val = params[key];
      if (val === undefined) throw new Error(`Missing route param: ${key}`);
      return encodeURIComponent(val);
    });
  }
  if (query && Object.keys(query).length > 0) {
    const qs = new URLSearchParams();
    for (const [k, v] of Object.entries(query)) {
      if (v !== undefined && v !== null) qs.append(k, String(v));
    }
    const qStr = qs.toString();
    if (qStr) {
      const sep = path.includes('?') ? '&' : '?';
      path = `${path}${sep}${qStr}`;
    }
  }
  return path;
}
